[package]
name = "twitchat"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0.44"
console_error_panic_hook = "0.1.7"
console_log = "0.2.0"
irc-proto = { version = "0.15.0", default-features = false }
log = { version = "0.4.14", features = ["release_max_level_info"] }
serde = { version = "1.0.130", features = ["derive"] }
serde_qs = "0.8.5"
yew = "0.18.0"
yewtil = "0.4.0"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
