[advisories]
version = 2
ignore = ["RUSTSEC-2021-0153"]

[licenses]
version = 2
allow = [
    "Apache-2.0",
    "BSL-1.0",
    "CC0-1.0",
    "MIT",
    "MPL-2.0",
    "Zlib",
]
exceptions = [
    { name = "twitchat", allow = ["AGPL-3.0"] },
    { name = "unicode-ident", allow = ["Unicode-DFS-2016"] },
]

[bans]
skip = [
    { name = "http", version = "0.2" },
]
