[licenses]
allow = [
    "CC0-1.0",
    "MPL-2.0",
]
allow-osi-fsf-free = "both"
exceptions = [
    { name = "twitchat", allow = ["AGPL-3.0"] },
]

[bans]
wildcards = "deny"
skip = [
    { name = "cfg-if", version = "=0.1.10" },
]
